spring:
  application:
    name: ite-3rd-ecommerce
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: ${PASSWORD}
    url: ${URL}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 8098
file:
  client-path: /file
  storage-location: D:\\ITE-File Upload Testing\\
  base-URI: http://localhost:${server.port}${file.client-path}/